name: Deploy to Amazon S3

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        id: code-checkout
        uses: actions/checkout@v3

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build and deploy
        id: build-deploy
        run: |
          ls
          pwd
          npm run build
          aws s3 sync build/ s3://mymobile-front-dev
